sudo: false
language: node_js
node_js:
  - '8.10.0'
script:
  - yarn install
  - yarn test --coverage
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
